### ISSUE TITLE
Add "files" key to package.json

### ISSUE THREAD

**Issue by ascariandrea** [buildo/babel-preset-buildo#4]
## description
Define `files` in `package.json` to declare which files (or folders) have to be included in the published package.
> The "files" field is an array of files to include in your project. If you name a folder in the array, then it will also include the files inside that folder. (Unless they would be ignored by another rule.)

## how to reproduce
- `npm publish` doesn't publish `lib` folder

## specs
`"files": ["lib"]`

## misc
{optional: other useful info}

**Comment by giogonzo** [comment]
@ascariandrea this could be even better in general: https://docs.npmjs.com/files/package.json#files
